// 商談フィードバック — deterministic analysis of a sales conversation, for
// coaching the seller after (or during) the call.
//
// WHY NO MODEL IS INVOLVED
// ------------------------
// Every number here is computed in JavaScript from timestamps and text. None
// of it is generated by Gemini Nano. A small on-device model asked to critique
// a sales call will produce fluent, generic advice that sounds authoritative
// and is grounded in nothing — and unlike a wrong summary, wrong coaching
// changes how someone does their job. Numbers a rep can argue with are worth
// more than prose they can't check.
//
// WHAT THIS CANNOT SEE
// --------------------
// Captions are text with a speaker and a timestamp. There is no audio, so
// there is no tone, no volume, no confidence, no talking-over-each-other, and
// no true speaking duration. Anything derived from timing is an estimate and
// is labelled 推定, exactly as in archive.js. Metrics that would need audio
// are simply absent rather than approximated — a fabricated "confidence
// score" is worse than no score.

(function (global) {
  "use strict";

  // Same run model as archive.js: consecutive utterances by one speaker closer
  // together than this are one continuous stretch of talking.
  const RUN_GAP_MS = 10000;

  // A run longer than this is worth flagging. 90s is roughly where a
  // discovery call stops being a conversation and becomes a presentation.
  const MONOLOGUE_MS = 90000;

  // Talk-ratio band for the seller. Widely-cited sales research puts the best
  // outcomes near 43%; this is a band around that, not a hard rule, and the UI
  // says so. It is a heuristic borrowed from the industry, not a measurement.
  const TALK_RATIO_LOW = 0.35;
  const TALK_RATIO_HIGH = 0.55;

  // Long enough that the customer has genuinely gone quiet rather than just
  // pausing for breath.
  const CUSTOMER_SILENT_MS = 180000;

  // Polite Japanese puts the question marker at the end, so this matches on the
  // sentence-final form. The past and negative forms (ましたか / ませんか /
  // でしたか) were missing until 2026-08: 「どうお考えでしたか」 simply did not
  // count as a question, which under-reported every seller who asks about what
  // a customer has already tried — exactly the discovery questions that matter.
  const QUESTION_RE =
    /[?？]\s*$|(?:ですか|ですかね|ますか|ますかね|ましたか|ませんか|ましょうか|でしたか|でしょうか|ますでしょうか|ませんでしょうか|かな|どう(?:です|でしょう)|いかが)[。．…]?\s*$/;

  // Zoom's own ASR often drops fillers before they ever reach us, so a low
  // count is not evidence of clean speech. The UI has to say that rather than
  // congratulate someone for a number that may just mean "captions were tidy".
  const FILLERS = ["あの", "あのー", "えっと", "えー", "まぁ", "まあ", "そのー", "なんか", "ええと"];

  const NEXT_STEP_RE =
    /(次回|次の(?:お)?打ち合わせ|日程|スケジュール|改めて|お見積|見積り|見積もり|ご提案|提案書|持ち帰|検討いた|ご連絡いたし|アポ)/;

  // An "open" question invites an explanation; a closed one can be answered
  // やはい/いいえ. The distinction is the whole of discovery quality, and it is
  // the reason a raw question *count* flatters a seller who only ever asks
  // 「ご興味ありますか」. Detected by interrogative, not by sentiment, so a user
  // can always see which word made it open.
  const OPEN_Q_RE =
    /(何|なに|なん[のでか]|どう(?:いう|やって|いった)?|どのよう|どの|どれ|どんな|どういっ|なぜ|どうして|いつ(?:頃)?|どこ|どちら|誰|だれ|いかが|教えて(?:いただ|くださ)|聞かせて|お聞かせ)/;

  // Discovery coverage. Each topic is the kind of thing a seller is supposed to
  // leave a first meeting knowing; leaving one blank is the single most common
  // reason a deal stalls later for reasons nobody wrote down.
  //
  // These are ordinary qualification topics (current state / pain / impact /
  // budget / decision process / timing), expressed here as our own keyword
  // sets. A hit always carries the line that produced it, so "予算に触れた" can
  // be checked against the transcript rather than believed.
  const COVERAGE = [
    {
      key: "current",
      label: "現状",
      re: /(現在|今[はの]|既存|使って(?:いる|います|らっしゃ)|運用され|運用して|体制|今のところ|現状)/,
    },
    {
      key: "problem",
      label: "課題",
      re: /(課題|困って|お困り|問題|悩み|不便|手間|大変|うまくいっ(?:て|ていな)|ボトルネック|ペイン)/,
    },
    {
      // Deliberately not matching bare どれくらい／どのくらい: they are just as
      // often asking a price, which would light up 影響 on every call that
      // mentioned money and make the checklist worthless.
      key: "impact",
      label: "影響",
      re: /(影響|工数|時間がかか|手間がかか|残業|負荷|損失|機会損失|件数|人日|生産性|効果|インパクト)/,
    },
    {
      key: "budget",
      label: "予算",
      re: /(予算|費用|金額|お値段|価格|コスト感|ご予算|いくら|料金)/,
    },
    {
      key: "authority",
      label: "決裁",
      re: /(決裁|決定|ご判断|稟議|承認|上司|役員|部長|社長|決められ|意思決定|どなたが)/,
    },
    {
      // Bare 開始 used to be here and matched 「運用開始後のサポート」 — a
      // support promise, not a timing answer. Anything that only means "starts"
      // has to carry a when- word beside it to count.
      key: "timing",
      label: "時期",
      re: /(時期|いつ(?:頃|から|まで)|スケジュール|導入(?:時期|は?いつ)|開始(?:時期|時点|は?いつ)|来月|再来月|来期|今期|年度内|納期|タイミング)/,
    },
  ];

  // A customer concern. Detecting it is easy; the useful part is whether the
  // seller did anything about it, which is why every hit is paired with a
  // window afterwards (below) rather than just counted.
  const OBJECTION_RE =
    /(高い|高く|予算(?:が|は)(?:厳し|合わ|足り)|厳しい|難しい|不安|リスク|心配|他社|比較|検討し(?:ます|たい)|持ち帰(?:り|ります)|今[はじ]ゃ?ない|時期尚早|必要(?:性|ない)|うちには)/;

  // How long after a concern the seller still counts as having responded to it.
  // Past this the conversation has moved on and the objection was dropped.
  const OBJECTION_WINDOW_MS = 120000;

  // No open question for this long, mid-call, means the call has stopped being
  // discovery and become a presentation.
  const OPEN_Q_DROUGHT_MS = 300000;

  // Only start nagging about unchecked coverage once the call is long enough
  // that there was realistically time to get to it.
  const COVERAGE_REMINDER_MS = 900000;

  /** Groups a speaker's utterances into continuous runs. */
  function runsFor(transcript, name) {
    const lines = transcript.filter((l) => (l.speaker || "") === name).sort((a, b) => a.at - b.at);
    const runs = [];
    let cur = null;

    for (const line of lines) {
      if (cur && line.at - cur.lastAt <= RUN_GAP_MS) {
        cur.lastAt = line.at;
        cur.lines.push(line);
      } else {
        if (cur) runs.push(cur);
        cur = { startAt: line.at, lastAt: line.at, lines: [line] };
      }
    }
    if (cur) runs.push(cur);

    // A run's span understates it by the length of its final utterance, which
    // has no following timestamp — same chars/sec fallback archive.js uses, so
    // the two never disagree about how long someone spoke.
    for (const r of runs) {
      const tail = r.lines[r.lines.length - 1];
      r.ms = r.lastAt - r.startAt + Math.min((tail.text || "").length / 7 * 1000, 30000);
    }
    return runs;
  }

  function speakingMs(transcript, name) {
    return runsFor(transcript, name).reduce((sum, r) => sum + r.ms, 0);
  }

  function countQuestions(transcript, name) {
    return transcript.filter((l) => (l.speaker || "") === name && QUESTION_RE.test((l.text || "").trim())).length;
  }

  /** Every question `name` asked, split by whether it invites an explanation. */
  function questionsFor(transcript, name) {
    const open = [];
    const closed = [];
    for (const l of transcript) {
      if ((l.speaker || "") !== name) continue;
      const text = (l.text || "").trim();
      if (!QUESTION_RE.test(text)) continue;
      const hit = { at: l.at, speaker: l.speaker, text };
      if (OPEN_Q_RE.test(text)) open.push(hit);
      else closed.push(hit);
    }
    return { open, closed };
  }

  /**
   * Which qualification topics came up, and the line that first raised each.
   *
   * Counts the topic as covered whoever said it — a customer volunteering
   * 「予算は300万くらい」 covers budget just as well as the seller asking, and
   * marking it uncovered because the seller did not personally say the word
   * would be pedantry the user would immediately disbelieve.
   */
  function coverageOf(transcript) {
    return COVERAGE.map((topic) => {
      const line = transcript.find((l) => topic.re.test(l.text || "")) ?? null;
      return {
        key: topic.key,
        label: topic.label,
        covered: Boolean(line),
        at: line?.at ?? null,
        speaker: line?.speaker ?? null,
        text: line?.text ?? "",
      };
    });
  }

  /**
   * Customer concerns, each marked with whether the seller engaged with it.
   *
   * "Addressed" deliberately means the seller *asked something* afterwards, not
   * merely that they spoke: talking over an objection is the failure mode this
   * is meant to catch, so a monologue in reply counts as unaddressed.
   */
  function objectionsOf(transcript, seller) {
    const sorted = [...transcript].sort((a, b) => a.at - b.at);
    const out = [];

    for (const line of sorted) {
      const who = line.speaker || "";
      if (who === seller) continue;
      if (!OBJECTION_RE.test(line.text || "")) continue;

      const replied = sorted.some(
        (l) =>
          (l.speaker || "") === seller &&
          l.at > line.at &&
          l.at - line.at <= OBJECTION_WINDOW_MS &&
          QUESTION_RE.test((l.text || "").trim()),
      );

      out.push({ at: line.at, speaker: who, text: line.text || "", addressed: replied });
    }
    return out;
  }

  function countFillers(transcript, name) {
    let n = 0;
    for (const l of transcript) {
      if ((l.speaker || "") !== name) continue;
      for (const f of FILLERS) {
        // Counts occurrences, not lines — one rambling sentence can carry
        // several and they all matter.
        n += (l.text || "").split(f).length - 1;
      }
    }
    return n;
  }

  /**
   * Median gap between the customer finishing and the seller starting.
   *
   * Median rather than mean: one long think after a hard question would drag
   * a mean somewhere unrepresentative, and the interesting signal is the
   * habitual pace, not the outlier.
   */
  function responseLatencyMs(transcript, seller) {
    const sorted = [...transcript].sort((a, b) => a.at - b.at);
    const gaps = [];
    for (let i = 1; i < sorted.length; i++) {
      const prev = sorted[i - 1];
      const cur = sorted[i];
      if ((prev.speaker || "") !== seller && (cur.speaker || "") === seller) {
        const gap = cur.at - prev.at;
        // Beyond this it is a new topic or a break, not a response.
        if (gap > 0 && gap < 30000) gaps.push(gap);
      }
    }
    if (!gaps.length) return null;
    gaps.sort((a, b) => a - b);
    return gaps[Math.floor(gaps.length / 2)];
  }

  /**
   * Full report for one meeting.
   *
   * `seller` must be an exact speaker name. Everyone else is treated as the
   * customer side — deliberately, since a call often has several people from
   * the buyer and lumping them together is what the talk ratio is about.
   * Returns null when the seller never speaks, rather than a report full of
   * zeroes that looks like a terrible call.
   */
  function analyze(record, seller) {
    const transcript = record?.transcript ?? [];
    if (!transcript.length || !seller) return null;

    const names = [...new Set(transcript.map((l) => l.speaker || ""))];
    if (!names.includes(seller)) return null;

    const others = names.filter((n) => n !== seller);
    const sellerMs = speakingMs(transcript, seller);
    const otherMs = others.reduce((sum, n) => sum + speakingMs(transcript, n), 0);
    const totalMs = sellerMs + otherMs;

    const sellerRuns = runsFor(transcript, seller);
    const longestSeller = sellerRuns.reduce((m, r) => Math.max(m, r.ms), 0);
    const longestCustomer = others.reduce(
      (m, n) => Math.max(m, runsFor(transcript, n).reduce((mm, r) => Math.max(mm, r.ms), 0)),
      0,
    );

    // Engagement trend: the customer's share of talking in each half. Rising
    // usually means the conversation opened up; falling often means it turned
    // into a pitch.
    const start = Math.min(...transcript.map((l) => l.at));
    const end = Math.max(...transcript.map((l) => l.at));
    const mid = start + (end - start) / 2;
    const firstHalf = transcript.filter((l) => l.at <= mid);
    const secondHalf = transcript.filter((l) => l.at > mid);
    const shareOf = (slice) => {
      if (!slice.length) return null;
      const s = speakingMs(slice, seller);
      const o = others.reduce((sum, n) => sum + speakingMs(slice, n), 0);
      return s + o > 0 ? o / (s + o) : null;
    };

    const nextStep = transcript.find((l) => NEXT_STEP_RE.test(l.text || "")) ?? null;

    const sellerQuestions = questionsFor(transcript, seller);
    const coverage = coverageOf(transcript);
    const objections = objectionsOf(transcript, seller);
    const askedTotal = sellerQuestions.open.length + sellerQuestions.closed.length;

    return {
      seller,
      customers: others,
      totalMs,
      sellerMs,
      customerMs: otherMs,
      talkRatio: totalMs > 0 ? sellerMs / totalMs : null,
      longestSellerMonologueMs: longestSeller,
      longestCustomerMonologueMs: longestCustomer,
      monologues: sellerRuns
        .filter((r) => r.ms >= MONOLOGUE_MS)
        .map((r) => ({ startAt: r.startAt, ms: r.ms, preview: r.lines[0]?.text ?? "" })),
      questionsBySeller: countQuestions(transcript, seller),
      questionsByCustomer: others.reduce((sum, n) => sum + countQuestions(transcript, n), 0),
      openQuestions: sellerQuestions.open,
      closedQuestions: sellerQuestions.closed,
      // Null rather than 0 when nothing was asked: "0% open" reads as a
      // judgement on the questions, and there were none to judge.
      openQuestionRate: askedTotal > 0 ? sellerQuestions.open.length / askedTotal : null,
      coverage,
      coveredCount: coverage.filter((c) => c.covered).length,
      coverageTotal: coverage.length,
      objections,
      unresolvedObjections: objections.filter((o) => !o.addressed),
      fillersBySeller: countFillers(transcript, seller),
      sellerChars: transcript.reduce(
        (sum, l) => sum + ((l.speaker || "") === seller ? (l.text || "").length : 0),
        0,
      ),
      responseLatencyMs: responseLatencyMs(transcript, seller),
      customerShareFirstHalf: shareOf(firstHalf),
      customerShareSecondHalf: shareOf(secondHalf),
      nextStep: nextStep ? { at: nextStep.at, speaker: nextStep.speaker, text: nextStep.text } : null,
      meetingStartAt: start,
      meetingEndAt: end,
    };
  }

  // Below this many past meetings there is no such thing as "your average" —
  // one previous call is an anecdote, and dressing it up as a personal baseline
  // would be exactly the invented metric this codebase refuses to ship.
  const MIN_BASELINE_MEETINGS = 3;

  function median(xs) {
    const v = xs.filter((x) => typeof x === "number" && Number.isFinite(x)).sort((a, b) => a - b);
    if (!v.length) return null;
    return v[Math.floor(v.length / 2)];
  }

  /**
   * The seller's own history, from meetings already in the archive.
   *
   * This is what makes the feedback theirs rather than generic: a 60% talk
   * ratio means nothing in the abstract, but "higher than your usual 44%" is
   * something the person can act on, and it cannot be cloned out of the
   * extension source because it is built from their own past calls.
   *
   * Returns null below MIN_BASELINE_MEETINGS rather than a shaky average.
   */
  function baseline(records, seller, { excludeId = null } = {}) {
    if (!Array.isArray(records) || !seller) return null;

    const reports = records
      .filter((r) => r && r.id !== excludeId)
      .map((r) => analyze(r, seller))
      .filter(Boolean);

    if (reports.length < MIN_BASELINE_MEETINGS) {
      return { meetings: reports.length, enough: false };
    }

    const coverageRate = {};
    for (const topic of COVERAGE) {
      const hits = reports.filter((rep) => rep.coverage.find((c) => c.key === topic.key)?.covered).length;
      coverageRate[topic.key] = hits / reports.length;
    }

    return {
      meetings: reports.length,
      enough: true,
      talkRatio: median(reports.map((r) => r.talkRatio)),
      openQuestionRate: median(reports.map((r) => r.openQuestionRate)),
      questionsBySeller: median(reports.map((r) => r.questionsBySeller)),
      coveredCount: median(reports.map((r) => r.coveredCount)),
      coverageRate,
    };
  }

  /**
   * Observations worth showing, ordered most-actionable first.
   *
   * Every item states the measured fact alongside the suggestion, so the rep
   * can disagree with the interpretation while still trusting the number.
   * `liveNowMs` turns this into the realtime path: pass the current clock and
   * it also reports what is happening right now (mid-monologue, customer gone
   * quiet), not just what already happened.
   */
  function nudges(report, { liveNowMs = null, baseline: base = null } = {}) {
    if (!report) return [];
    const out = [];
    const mins = (ms) => Math.round(ms / 60000);
    const secs = (ms) => Math.round(ms / 1000);
    const pctOf = (x) => Math.round(x * 100);

    if (report.talkRatio != null) {
      const pct = Math.round(report.talkRatio * 100);
      if (report.talkRatio > TALK_RATIO_HIGH) {
        out.push({
          level: "warn",
          metric: "talkRatio",
          text: `あなたの発言が全体の約${pct}%です。質問を投げて、お客様に話していただく時間を増やしましょう。`,
        });
      } else if (report.talkRatio < TALK_RATIO_LOW) {
        out.push({
          level: "info",
          metric: "talkRatio",
          text: `あなたの発言は全体の約${pct}%です。聞けている一方で、提案や要約が不足していないか確認しましょう。`,
        });
      } else {
        out.push({
          level: "ok",
          metric: "talkRatio",
          text: `発言比率は約${pct}%で、バランスの取れた範囲です。`,
        });
      }
    }

    if (report.longestSellerMonologueMs >= MONOLOGUE_MS) {
      out.push({
        level: "warn",
        metric: "monologue",
        text: `最長で${secs(report.longestSellerMonologueMs)}秒続けて話しています。途中で「ここまでいかがですか」と挟むと、相手の反応を確認できます。`,
      });
    }

    if (report.questionsBySeller === 0) {
      out.push({
        level: "warn",
        metric: "questions",
        text: "質問が検出されませんでした。課題を引き出す質問を用意しておきましょう。",
      });
    } else {
      out.push({
        level: "info",
        metric: "questions",
        text: `質問を${report.questionsBySeller}回しています（お客様からは${report.questionsByCustomer}回）。`,
      });
    }

    // Question *quality*. A high count made entirely of 「〜ですよね」 is worse
    // than three questions that made the customer explain something, so this is
    // reported separately rather than folded into the count above.
    if (report.openQuestionRate != null) {
      const openN = report.openQuestions.length;
      const closedN = report.closedQuestions.length;
      if (report.openQuestionRate < 0.3) {
        out.push({
          level: "warn",
          metric: "openQuestions",
          text: `「はい／いいえ」で答えられる質問が中心です（オープン${openN}件・クローズド${closedN}件）。「どのように」「なぜ」で始まる質問を増やすと、背景を話していただけます。`,
        });
      } else {
        out.push({
          level: "ok",
          metric: "openQuestions",
          text: `オープンな質問が${openN}件（全${openN + closedN}件中）。相手に説明していただく形になっています。`,
        });
      }
    }

    // Coverage. Named explicitly — "3/6 covered" is useless without knowing
    // which three are missing, since 予算 and 決裁 are the ones that sink deals.
    const missing = report.coverage.filter((c) => !c.covered);
    if (missing.length) {
      out.push({
        level: missing.length >= 3 ? "warn" : "info",
        metric: "coverage",
        text: `未確認の項目があります：${missing.map((c) => c.label).join("・")}。次回までに押さえておきたい点です。`,
      });
    } else {
      out.push({
        level: "ok",
        metric: "coverage",
        text: "現状・課題・影響・予算・決裁・時期のすべてに触れています。",
      });
    }

    // An objection nobody answered is the most expensive thing in the call.
    if (report.unresolvedObjections.length) {
      const first = report.unresolvedObjections[0];
      out.push({
        level: "warn",
        metric: "objections",
        text: `お客様の懸念に質問で返せていない箇所が${report.unresolvedObjections.length}件あります（例:「${first.text.slice(0, 30)}」）。掘り下げる質問で背景を確認しましょう。`,
      });
    } else if (report.objections.length) {
      out.push({
        level: "ok",
        metric: "objections",
        text: `お客様の懸念${report.objections.length}件すべてに質問で応じています。`,
      });
    }

    // Comparison against the seller's own past calls. Deliberately last among
    // the post-hoc items: it is context for the numbers above, not a finding of
    // its own, and it only appears once there is enough history to mean it.
    if (base?.enough) {
      if (report.talkRatio != null && base.talkRatio != null) {
        const d = report.talkRatio - base.talkRatio;
        if (Math.abs(d) >= 0.1) {
          out.push({
            level: d > 0 ? "warn" : "info",
            metric: "baselineTalkRatio",
            text: `発言比率${pctOf(report.talkRatio)}%は、直近${base.meetings}件の平均${pctOf(base.talkRatio)}%より${d > 0 ? "高め" : "低め"}です。`,
          });
        }
      }
      if (report.openQuestionRate != null && base.openQuestionRate != null) {
        const d = report.openQuestionRate - base.openQuestionRate;
        if (d <= -0.15) {
          out.push({
            level: "warn",
            metric: "baselineOpenQuestions",
            text: `オープンな質問の割合${pctOf(report.openQuestionRate)}%は、普段の${pctOf(base.openQuestionRate)}%を下回っています。`,
          });
        } else if (d >= 0.15) {
          out.push({
            level: "ok",
            metric: "baselineOpenQuestions",
            text: `オープンな質問の割合${pctOf(report.openQuestionRate)}%は、普段の${pctOf(base.openQuestionRate)}%を上回っています。`,
          });
        }
      }
    }

    if (report.customerShareFirstHalf != null && report.customerShareSecondHalf != null) {
      const d = report.customerShareSecondHalf - report.customerShareFirstHalf;
      if (d <= -0.15) {
        out.push({
          level: "warn",
          metric: "engagement",
          text: "後半にかけてお客様の発言が減っています。提案が一方通行になっていないか振り返りましょう。",
        });
      } else if (d >= 0.15) {
        out.push({
          level: "ok",
          metric: "engagement",
          text: "後半にかけてお客様の発言が増えています。話を引き出せています。",
        });
      }
    }

    if (!report.nextStep) {
      out.push({
        level: "warn",
        metric: "nextStep",
        text: "次のステップ（日程・提案・見積など）に触れた発言が見つかりませんでした。",
      });
    } else {
      out.push({ level: "ok", metric: "nextStep", text: "次のステップに触れています。" });
    }

    if (report.fillersBySeller > 0) {
      const per100 = report.sellerChars > 0 ? (report.fillersBySeller / report.sellerChars) * 100 : 0;
      if (per100 >= 1.5) {
        out.push({
          level: "info",
          metric: "fillers",
          text: `「あの」「えっと」等が${report.fillersBySeller}回検出されました（100文字あたり${per100.toFixed(1)}回）。`,
        });
      }
    }

    // Live-only: what is happening at this moment, which a post-hoc report
    // cannot tell you in time to do anything about it.
    if (liveNowMs != null) {
      const sinceCustomer = report.customers.length
        ? liveNowMs - Math.max(...report.customers.map((n) => lastAtOf(report, n)), 0)
        : null;
      if (sinceCustomer != null && Number.isFinite(sinceCustomer) && sinceCustomer >= CUSTOMER_SILENT_MS) {
        out.unshift({
          level: "warn",
          metric: "customerSilent",
          text: `お客様の発言が${mins(sinceCustomer)}分ありません。問いかけてみましょう。`,
        });
      }

      // Still talking, right now, past the monologue threshold. The post-hoc
      // version of this tells you what you did; only this one can stop it.
      if (report.currentRunMs != null && report.currentRunMs >= MONOLOGUE_MS) {
        out.unshift({
          level: "warn",
          metric: "monologueNow",
          text: `${secs(report.currentRunMs)}秒続けて話しています。一度区切って、相手に確認しましょう。`,
        });
      }

      // Discovery has stalled: questions may still be flowing, but none of them
      // are asking the customer to explain anything.
      const lastOpen = report.openQuestions.length
        ? report.openQuestions[report.openQuestions.length - 1].at
        : report.meetingStartAt;
      const sinceOpen = liveNowMs - lastOpen;
      if (Number.isFinite(sinceOpen) && sinceOpen >= OPEN_Q_DROUGHT_MS) {
        out.unshift({
          level: "warn",
          metric: "openQuestionDrought",
          text: `${mins(sinceOpen)}分間、オープンな質問がありません。「どのように」「なぜ」で背景を伺いましょう。`,
        });
      }

      // A concern raised and not yet picked up, while there is still time to.
      const openObjection = report.unresolvedObjections.find(
        (o) => liveNowMs - o.at <= OBJECTION_WINDOW_MS,
      );
      if (openObjection) {
        out.unshift({
          level: "warn",
          metric: "objectionNow",
          text: `「${openObjection.text.slice(0, 24)}」への確認がまだです。今のうちに掘り下げましょう。`,
        });
      }

      // Late in a long call, name what is still unknown while it can still be
      // asked rather than written up as a gap afterwards.
      const elapsed = liveNowMs - report.meetingStartAt;
      const stillMissing = report.coverage.filter((c) => !c.covered);
      if (elapsed >= COVERAGE_REMINDER_MS && stillMissing.length) {
        out.push({
          level: "info",
          metric: "coverageNow",
          text: `未確認：${stillMissing.map((c) => c.label).join("・")}。残り時間で確認しておきましょう。`,
        });
      }
    }

    return out;
  }

  // Filled in by analyze() so nudges() can answer "when did this person last
  // speak" without being handed the transcript a second time.
  function lastAtOf(report, name) {
    return report._lastAt?.[name] ?? 0;
  }

  /** analyze() + the per-speaker last-spoke map the live nudges need. */
  function analyzeLive(record, seller, nowMs, { baseline: base = null } = {}) {
    const report = analyze(record, seller);
    if (!report) return { report: null, nudges: [] };
    report._lastAt = {};
    for (const l of record.transcript) {
      const n = l.speaker || "";
      report._lastAt[n] = Math.max(report._lastAt[n] ?? 0, l.at);
    }

    // How long the seller has been talking *without stopping, as of now*.
    // Null unless they are actually mid-run: once the gap exceeds RUN_GAP_MS
    // the run is over, and reporting its length as ongoing would nag someone
    // for a monologue they already ended.
    const runs = runsFor(record.transcript, seller);
    const last = runs[runs.length - 1] ?? null;
    report.currentRunMs =
      last && nowMs - last.lastAt <= RUN_GAP_MS ? nowMs - last.startAt : null;

    return { report, nudges: nudges(report, { liveNowMs: nowMs, baseline: base }) };
  }

  // Which speaker is "me" is a UI preference, not meeting data, so it lives
  // beside the archive rather than inside a record — that keeps the stored
  // meeting shape identical whether or not anyone ever asked for feedback.
  const SELLER_KEY = "coachSellerByMeeting";

  async function getSeller(meetingId) {
    const got = await chrome.storage.local.get(SELLER_KEY);
    return got?.[SELLER_KEY]?.[meetingId] ?? null;
  }

  async function setSeller(meetingId, name) {
    const got = await chrome.storage.local.get(SELLER_KEY);
    const map = got?.[SELLER_KEY] ?? {};
    if (name) map[meetingId] = name;
    else delete map[meetingId];
    await chrome.storage.local.set({ [SELLER_KEY]: map });
  }

  global.MeetingCoach = {
    SELLER_KEY,
    getSeller,
    setSeller,
    RUN_GAP_MS,
    MONOLOGUE_MS,
    TALK_RATIO_LOW,
    TALK_RATIO_HIGH,
    CUSTOMER_SILENT_MS,
    QUESTION_RE,
    FILLERS,
    NEXT_STEP_RE,
    OPEN_Q_RE,
    OBJECTION_RE,
    OBJECTION_WINDOW_MS,
    OPEN_Q_DROUGHT_MS,
    COVERAGE_REMINDER_MS,
    COVERAGE,
    MIN_BASELINE_MEETINGS,
    analyze,
    analyzeLive,
    nudges,
    baseline,
    questionsFor,
    coverageOf,
    objectionsOf,
  };
})(self);
