// 商談フィードバック — deterministic analysis of a sales conversation, for
// coaching the seller after (or during) the call.
//
// WHY NO MODEL IS INVOLVED
// ------------------------
// Every number here is computed in JavaScript from timestamps and text. None
// of it is generated by Gemini Nano. A small on-device model asked to critique
// a sales call will produce fluent, generic advice that sounds authoritative
// and is grounded in nothing — and unlike a wrong summary, wrong coaching
// changes how someone does their job. Numbers a rep can argue with are worth
// more than prose they can't check.
//
// WHAT THIS CANNOT SEE
// --------------------
// Captions are text with a speaker and a timestamp. There is no audio, so
// there is no tone, no volume, no confidence, no talking-over-each-other, and
// no true speaking duration. Anything derived from timing is an estimate and
// is labelled 推定, exactly as in archive.js. Metrics that would need audio
// are simply absent rather than approximated — a fabricated "confidence
// score" is worse than no score.

(function (global) {
  "use strict";

  // Same run model as archive.js: consecutive utterances by one speaker closer
  // together than this are one continuous stretch of talking.
  const RUN_GAP_MS = 10000;

  // A run longer than this is worth flagging. 90s is roughly where a
  // discovery call stops being a conversation and becomes a presentation.
  const MONOLOGUE_MS = 90000;

  // Talk-ratio band for the seller. Widely-cited sales research puts the best
  // outcomes near 43%; this is a band around that, not a hard rule, and the UI
  // says so. It is a heuristic borrowed from the industry, not a measurement.
  const TALK_RATIO_LOW = 0.35;
  const TALK_RATIO_HIGH = 0.55;

  // Long enough that the customer has genuinely gone quiet rather than just
  // pausing for breath.
  const CUSTOMER_SILENT_MS = 180000;

  const QUESTION_RE = /[?？]\s*$|(?:ですか|ますか|でしょうか|ますかね|かな|どう(?:です|でしょう)|いかが)[。．…]?\s*$/;

  // Zoom's own ASR often drops fillers before they ever reach us, so a low
  // count is not evidence of clean speech. The UI has to say that rather than
  // congratulate someone for a number that may just mean "captions were tidy".
  const FILLERS = ["あの", "あのー", "えっと", "えー", "まぁ", "まあ", "そのー", "なんか", "ええと"];

  const NEXT_STEP_RE =
    /(次回|次の(?:お)?打ち合わせ|日程|スケジュール|改めて|お見積|見積り|見積もり|ご提案|提案書|持ち帰|検討いた|ご連絡いたし|アポ)/;

  /** Groups a speaker's utterances into continuous runs. */
  function runsFor(transcript, name) {
    const lines = transcript.filter((l) => (l.speaker || "") === name).sort((a, b) => a.at - b.at);
    const runs = [];
    let cur = null;

    for (const line of lines) {
      if (cur && line.at - cur.lastAt <= RUN_GAP_MS) {
        cur.lastAt = line.at;
        cur.lines.push(line);
      } else {
        if (cur) runs.push(cur);
        cur = { startAt: line.at, lastAt: line.at, lines: [line] };
      }
    }
    if (cur) runs.push(cur);

    // A run's span understates it by the length of its final utterance, which
    // has no following timestamp — same chars/sec fallback archive.js uses, so
    // the two never disagree about how long someone spoke.
    for (const r of runs) {
      const tail = r.lines[r.lines.length - 1];
      r.ms = r.lastAt - r.startAt + Math.min((tail.text || "").length / 7 * 1000, 30000);
    }
    return runs;
  }

  function speakingMs(transcript, name) {
    return runsFor(transcript, name).reduce((sum, r) => sum + r.ms, 0);
  }

  function countQuestions(transcript, name) {
    return transcript.filter((l) => (l.speaker || "") === name && QUESTION_RE.test((l.text || "").trim())).length;
  }

  function countFillers(transcript, name) {
    let n = 0;
    for (const l of transcript) {
      if ((l.speaker || "") !== name) continue;
      for (const f of FILLERS) {
        // Counts occurrences, not lines — one rambling sentence can carry
        // several and they all matter.
        n += (l.text || "").split(f).length - 1;
      }
    }
    return n;
  }

  /**
   * Median gap between the customer finishing and the seller starting.
   *
   * Median rather than mean: one long think after a hard question would drag
   * a mean somewhere unrepresentative, and the interesting signal is the
   * habitual pace, not the outlier.
   */
  function responseLatencyMs(transcript, seller) {
    const sorted = [...transcript].sort((a, b) => a.at - b.at);
    const gaps = [];
    for (let i = 1; i < sorted.length; i++) {
      const prev = sorted[i - 1];
      const cur = sorted[i];
      if ((prev.speaker || "") !== seller && (cur.speaker || "") === seller) {
        const gap = cur.at - prev.at;
        // Beyond this it is a new topic or a break, not a response.
        if (gap > 0 && gap < 30000) gaps.push(gap);
      }
    }
    if (!gaps.length) return null;
    gaps.sort((a, b) => a - b);
    return gaps[Math.floor(gaps.length / 2)];
  }

  /**
   * Full report for one meeting.
   *
   * `seller` must be an exact speaker name. Everyone else is treated as the
   * customer side — deliberately, since a call often has several people from
   * the buyer and lumping them together is what the talk ratio is about.
   * Returns null when the seller never speaks, rather than a report full of
   * zeroes that looks like a terrible call.
   */
  function analyze(record, seller) {
    const transcript = record?.transcript ?? [];
    if (!transcript.length || !seller) return null;

    const names = [...new Set(transcript.map((l) => l.speaker || ""))];
    if (!names.includes(seller)) return null;

    const others = names.filter((n) => n !== seller);
    const sellerMs = speakingMs(transcript, seller);
    const otherMs = others.reduce((sum, n) => sum + speakingMs(transcript, n), 0);
    const totalMs = sellerMs + otherMs;

    const sellerRuns = runsFor(transcript, seller);
    const longestSeller = sellerRuns.reduce((m, r) => Math.max(m, r.ms), 0);
    const longestCustomer = others.reduce(
      (m, n) => Math.max(m, runsFor(transcript, n).reduce((mm, r) => Math.max(mm, r.ms), 0)),
      0,
    );

    // Engagement trend: the customer's share of talking in each half. Rising
    // usually means the conversation opened up; falling often means it turned
    // into a pitch.
    const start = Math.min(...transcript.map((l) => l.at));
    const end = Math.max(...transcript.map((l) => l.at));
    const mid = start + (end - start) / 2;
    const firstHalf = transcript.filter((l) => l.at <= mid);
    const secondHalf = transcript.filter((l) => l.at > mid);
    const shareOf = (slice) => {
      if (!slice.length) return null;
      const s = speakingMs(slice, seller);
      const o = others.reduce((sum, n) => sum + speakingMs(slice, n), 0);
      return s + o > 0 ? o / (s + o) : null;
    };

    const nextStep = transcript.find((l) => NEXT_STEP_RE.test(l.text || "")) ?? null;

    return {
      seller,
      customers: others,
      totalMs,
      sellerMs,
      customerMs: otherMs,
      talkRatio: totalMs > 0 ? sellerMs / totalMs : null,
      longestSellerMonologueMs: longestSeller,
      longestCustomerMonologueMs: longestCustomer,
      monologues: sellerRuns
        .filter((r) => r.ms >= MONOLOGUE_MS)
        .map((r) => ({ startAt: r.startAt, ms: r.ms, preview: r.lines[0]?.text ?? "" })),
      questionsBySeller: countQuestions(transcript, seller),
      questionsByCustomer: others.reduce((sum, n) => sum + countQuestions(transcript, n), 0),
      fillersBySeller: countFillers(transcript, seller),
      sellerChars: transcript.reduce(
        (sum, l) => sum + ((l.speaker || "") === seller ? (l.text || "").length : 0),
        0,
      ),
      responseLatencyMs: responseLatencyMs(transcript, seller),
      customerShareFirstHalf: shareOf(firstHalf),
      customerShareSecondHalf: shareOf(secondHalf),
      nextStep: nextStep ? { at: nextStep.at, speaker: nextStep.speaker, text: nextStep.text } : null,
      meetingStartAt: start,
      meetingEndAt: end,
    };
  }

  /**
   * Observations worth showing, ordered most-actionable first.
   *
   * Every item states the measured fact alongside the suggestion, so the rep
   * can disagree with the interpretation while still trusting the number.
   * `liveNowMs` turns this into the realtime path: pass the current clock and
   * it also reports what is happening right now (mid-monologue, customer gone
   * quiet), not just what already happened.
   */
  function nudges(report, { liveNowMs = null } = {}) {
    if (!report) return [];
    const out = [];
    const mins = (ms) => Math.round(ms / 60000);
    const secs = (ms) => Math.round(ms / 1000);

    if (report.talkRatio != null) {
      const pct = Math.round(report.talkRatio * 100);
      if (report.talkRatio > TALK_RATIO_HIGH) {
        out.push({
          level: "warn",
          metric: "talkRatio",
          text: `あなたの発言が全体の約${pct}%です。質問を投げて、お客様に話していただく時間を増やしましょう。`,
        });
      } else if (report.talkRatio < TALK_RATIO_LOW) {
        out.push({
          level: "info",
          metric: "talkRatio",
          text: `あなたの発言は全体の約${pct}%です。聞けている一方で、提案や要約が不足していないか確認しましょう。`,
        });
      } else {
        out.push({
          level: "ok",
          metric: "talkRatio",
          text: `発言比率は約${pct}%で、バランスの取れた範囲です。`,
        });
      }
    }

    if (report.longestSellerMonologueMs >= MONOLOGUE_MS) {
      out.push({
        level: "warn",
        metric: "monologue",
        text: `最長で${secs(report.longestSellerMonologueMs)}秒続けて話しています。途中で「ここまでいかがですか」と挟むと、相手の反応を確認できます。`,
      });
    }

    if (report.questionsBySeller === 0) {
      out.push({
        level: "warn",
        metric: "questions",
        text: "質問が検出されませんでした。課題を引き出す質問を用意しておきましょう。",
      });
    } else {
      out.push({
        level: "info",
        metric: "questions",
        text: `質問を${report.questionsBySeller}回しています（お客様からは${report.questionsByCustomer}回）。`,
      });
    }

    if (report.customerShareFirstHalf != null && report.customerShareSecondHalf != null) {
      const d = report.customerShareSecondHalf - report.customerShareFirstHalf;
      if (d <= -0.15) {
        out.push({
          level: "warn",
          metric: "engagement",
          text: "後半にかけてお客様の発言が減っています。提案が一方通行になっていないか振り返りましょう。",
        });
      } else if (d >= 0.15) {
        out.push({
          level: "ok",
          metric: "engagement",
          text: "後半にかけてお客様の発言が増えています。話を引き出せています。",
        });
      }
    }

    if (!report.nextStep) {
      out.push({
        level: "warn",
        metric: "nextStep",
        text: "次のステップ（日程・提案・見積など）に触れた発言が見つかりませんでした。",
      });
    } else {
      out.push({ level: "ok", metric: "nextStep", text: "次のステップに触れています。" });
    }

    if (report.fillersBySeller > 0) {
      const per100 = report.sellerChars > 0 ? (report.fillersBySeller / report.sellerChars) * 100 : 0;
      if (per100 >= 1.5) {
        out.push({
          level: "info",
          metric: "fillers",
          text: `「あの」「えっと」等が${report.fillersBySeller}回検出されました（100文字あたり${per100.toFixed(1)}回）。`,
        });
      }
    }

    // Live-only: what is happening at this moment, which a post-hoc report
    // cannot tell you in time to do anything about it.
    if (liveNowMs != null) {
      const sinceCustomer = report.customers.length
        ? liveNowMs - Math.max(...report.customers.map((n) => lastAtOf(report, n)), 0)
        : null;
      if (sinceCustomer != null && Number.isFinite(sinceCustomer) && sinceCustomer >= CUSTOMER_SILENT_MS) {
        out.unshift({
          level: "warn",
          metric: "customerSilent",
          text: `お客様の発言が${mins(sinceCustomer)}分ありません。問いかけてみましょう。`,
        });
      }
    }

    return out;
  }

  // Filled in by analyze() so nudges() can answer "when did this person last
  // speak" without being handed the transcript a second time.
  function lastAtOf(report, name) {
    return report._lastAt?.[name] ?? 0;
  }

  /** analyze() + the per-speaker last-spoke map the live nudges need. */
  function analyzeLive(record, seller, nowMs) {
    const report = analyze(record, seller);
    if (!report) return { report: null, nudges: [] };
    report._lastAt = {};
    for (const l of record.transcript) {
      const n = l.speaker || "";
      report._lastAt[n] = Math.max(report._lastAt[n] ?? 0, l.at);
    }
    return { report, nudges: nudges(report, { liveNowMs: nowMs }) };
  }

  // Which speaker is "me" is a UI preference, not meeting data, so it lives
  // beside the archive rather than inside a record — that keeps the stored
  // meeting shape identical whether or not anyone ever asked for feedback.
  const SELLER_KEY = "coachSellerByMeeting";

  async function getSeller(meetingId) {
    const got = await chrome.storage.local.get(SELLER_KEY);
    return got?.[SELLER_KEY]?.[meetingId] ?? null;
  }

  async function setSeller(meetingId, name) {
    const got = await chrome.storage.local.get(SELLER_KEY);
    const map = got?.[SELLER_KEY] ?? {};
    if (name) map[meetingId] = name;
    else delete map[meetingId];
    await chrome.storage.local.set({ [SELLER_KEY]: map });
  }

  global.MeetingCoach = {
    SELLER_KEY,
    getSeller,
    setSeller,
    RUN_GAP_MS,
    MONOLOGUE_MS,
    TALK_RATIO_LOW,
    TALK_RATIO_HIGH,
    CUSTOMER_SILENT_MS,
    QUESTION_RE,
    FILLERS,
    NEXT_STEP_RE,
    analyze,
    analyzeLive,
    nudges,
  };
})(self);
